language: scala
scala:
  - 2.11.8

sudo: false

script: sbt "+ test" -Dloglevel=debug

jdk:
 - oraclejdk8

branches:
  only:
    - develop

addons:
  apt:
    packages:
      - oracle-java8-installer
